# Follow the rule: username = "password"
#username=["alice_foo","bob_bar"]

passwords={"alice_foo"="streamlit123","vijay"="123"}

#alice_foo = "streamlit123"
#bob_bar = "mycrazypw"

#alice_foo = "streamlit123"
#bob_bar = "mycrazypw"
